[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2


[[social]]
    identifier = "twitter"
    name = "X"
    url = "https://twitter.com/sokoX2"
    weight = 1

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/sokosun/"
    weight = 2